services:
  - type: web
    name: vita-fortis
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: EMAIL_ENABLED
        value: "false"
      - key: IMPORTAR_CATALOGO_FTW
        value: "true"
      - key: TOMCAT_NIO2
        value: "true"
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=75.0
