spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=INFO
vita-fortis.checkout.frete-fixo=${FRETE_FIXO:15.00}
vita-fortis.checkout.prazo-padrao-dias=${PRAZO_ENTREGA_DIAS:5}
