server.port=${PORT:8080}

spring.datasource.url=${JDBC_URL:jdbc:mysql://localhost:3306/vitafortis?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_general_ci&serverTimezone=America/Sao_Paulo}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:senha}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.flyway.enabled=false
spring.liquibase.enabled=false

logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
