import { FormEvent, useEffect, useState } from 'react'
import { Heart, KeyRound, MapPin, Package, Plus, ShieldCheck, Trash2, UserRound, X } from 'lucide-react'
import { Link, Navigate } from 'react-router-dom'
import { useAuth } from '../app/AuthContext'
import { api } from '../services/api'
import { isAdmin, isCollaborator, type Address, type AddressInput, type Order } from '../types/api'
import { date, money, titleCase } from '../utils/format'

const emptyAddress:AddressInput={apelido:'Casa',cep:'',logradouro:'',numero:'',complemento:'',bairro:'',cidade:'',uf:'',principal:false}

export function AccountPage(){
 const {user,updateUser}=useAuth();const [orders,setOrders]=useState<Order[]>([]);const [addresses,setAddresses]=useState<Address[]>([]);const [address,setAddress]=useState<(AddressInput&{id?:number})|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false)
 useEffect(()=>{if(user?.tipoUsuario==='CLIENTE')Promise.all([api.orders(user.id),api.addresses(user.id)]).then(([o,a])=>{setOrders(o);setAddresses(a)}).catch(e=>setMessage(e.message))},[user?.id,user?.tipoUsuario])
 if(!user)return <Navigate to="/entrar" replace/>;if(isAdmin(user))return <Navigate to="/admin" replace/>;if(isCollaborator(user))return <Navigate to="/colaborador" replace/>
 const profile=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{const next=await api.updateMe({nome:String(f.get('nome')),telefone:String(f.get('telefone')),aceitaComunicacoes:f.get('comunicacoes')==='on'});updateUser(next);setMessage('Perfil atualizado.')}catch(err){setMessage(err instanceof Error?err.message:'Falha ao atualizar.')}finally{setBusy(false)}}
 const password=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const nova=String(f.get('nova'));if(nova!==String(f.get('confirmacao'))){setMessage('A confirmação da nova senha não confere.');return}setBusy(true);try{await api.changePassword({senhaAtual:String(f.get('atual')),novaSenha:nova});form.reset();setMessage('Senha alterada com segurança. Entre novamente no próximo acesso.')}catch(err){setMessage(err instanceof Error?err.message:'Falha ao alterar senha.')}finally{setBusy(false)}}
 const saveAddress=async(e:FormEvent)=>{e.preventDefault();if(!address)return;setBusy(true);try{if(address.id)await api.updateAddress(user.id,address.id,address);else await api.createAddress(user.id,address);setAddresses(await api.addresses(user.id));setAddress(null);setMessage('Endereço salvo.')}catch(err){setMessage(err instanceof Error?err.message:'Falha ao salvar endereço.')}finally{setBusy(false)}}
 const removeAddress=async(id:number)=>{if(!confirm('Desativar este endereço?'))return;await api.removeAddress(user.id,id);setAddresses(await api.addresses(user.id));setMessage('Endereço removido.')}
 return <div className="page container account-page"><header className="page-header compact"><span className="eyebrow">Área do cliente</span><h1>Olá, {user.nome.split(' ')[0]}.</h1><p>Gerencie seus dados, endereços, segurança e acompanhe suas compras.</p></header>{message&&<div className="success-banner"><ShieldCheck/><span>{message}</span></div>}
 <div className="metric-grid"><article><Package/><span>Pedidos</span><strong>{orders.length}</strong></article><article><Heart/><span>Favoritos</span><Link to="/favoritos">Ver minha lista</Link></article><article><MapPin/><span>Endereços ativos</span><strong>{addresses.length}</strong></article></div>
 <div className="account-grid"><form className="chart-card form" onSubmit={profile}><h2><UserRound/> Dados pessoais</h2><label>Nome<input name="nome" required defaultValue={user.nome}/></label><label>E-mail<input disabled value={user.email}/></label><label>Telefone<input name="telefone" defaultValue={user.telefone}/></label><label className="check-row"><input name="comunicacoes" type="checkbox" defaultChecked={user.aceitaComunicacoes}/> Aceito receber comunicações</label><button className="button primary" disabled={busy}>Salvar perfil</button></form>
 <form className="chart-card form" onSubmit={password}><h2><KeyRound/> Alterar senha</h2><label>Senha atual<input name="atual" type="password" required/></label><label>Nova senha<input name="nova" type="password" minLength={8} required/></label><label>Confirmar nova senha<input name="confirmacao" type="password" minLength={8} required/></label><button className="button secondary" disabled={busy}>Atualizar senha</button></form></div>
 <section className="chart-card address-section"><header><div><h2><MapPin/> Meus endereços</h2><p>O endereço principal será selecionado automaticamente no checkout.</p></div><button className="button secondary" onClick={()=>setAddress({...emptyAddress,principal:addresses.length===0})}><Plus/> Novo endereço</button></header>{!addresses.length?<p className="empty-inline">Nenhum endereço cadastrado.</p>:<div className="address-grid">{addresses.map(a=><article key={a.id}><strong>{a.apelido||'Endereço'} {a.principal&&<span className="role-chip">Principal</span>}</strong><p>{a.logradouro}, {a.numero}{a.complemento&&` — ${a.complemento}`}<br/>{a.bairro}, {a.cidade}/{a.uf} — {a.cep}</p><footer><button onClick={()=>setAddress({...a})}>Editar</button><button className="danger" onClick={()=>void removeAddress(a.id)}><Trash2/> Remover</button></footer></article>)}</div>}</section>
 <section className="chart-card"><h2><Package/> Pedidos recentes</h2>{!orders.length?<p className="empty-inline">Você ainda não realizou pedidos.</p>:orders.slice(0,3).map(o=><Link className="recent-order" to="/pedidos" key={o.id}><span>Pedido #{o.id}<small>{date(o.dataPedido)}</small></span><b>{titleCase(o.status)} · {money(o.total)}</b></Link>)}{orders.length>0&&<Link className="text-link" to="/pedidos">Ver todos os pedidos</Link>}</section>
 {address&&<div className="modal-backdrop"><form className="admin-modal small" onSubmit={saveAddress}><header><h2>{address.id?'Editar':'Novo'} endereço</h2><button type="button" onClick={()=>setAddress(null)}><X/></button></header><div className="form-grid">{(['apelido','cep','logradouro','numero','complemento','bairro','cidade','uf'] as const).map(k=><label key={k}>{titleCase(k)}<input required={!['apelido','complemento'].includes(k)} maxLength={k==='uf'?2:undefined} value={String(address[k]||'')} onChange={e=>setAddress({...address,[k]:k==='uf'?e.target.value.toUpperCase():e.target.value})}/></label>)}<label className="check-row full"><input type="checkbox" checked={address.principal} onChange={e=>setAddress({...address,principal:e.target.checked})}/> Tornar principal</label></div><footer><button type="button" className="button secondary" onClick={()=>setAddress(null)}>Cancelar</button><button className="button primary">Salvar</button></footer></form></div>}</div>
}
