import { Eye, EyeOff, LockKeyhole } from 'lucide-react'
import { useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../app/AuthContext'

export function AuthPage() {
  const [mode, setMode] = useState<'login' | 'register'>('login'); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const { login, register } = useAuth(); const navigate = useNavigate(); const location = useLocation()
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); setBusy(true); const data = new FormData(event.currentTarget); try { if (mode === 'login') await login(String(data.get('email')), String(data.get('senha'))); else await register({ nome: String(data.get('nome')), email: String(data.get('email')), senha: String(data.get('senha')), cpf: String(data.get('cpf')), telefone: String(data.get('telefone') || '') }); const state = location.state as { from?: string } | null; navigate(state?.from || '/conta', { replace: true }) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível entrar.') } finally { setBusy(false) } }
  return <div className="auth-page"><div className="auth-visual"><div><span className="eyebrow light">Vita Fortis</span><h1>Seu progresso merece companhia.</h1><p>Acesse pedidos, sacola e seus dados em um só lugar.</p></div></div><section className="auth-card"><div className="auth-icon"><LockKeyhole /></div><h2>{mode === 'login' ? 'Boas-vindas de volta' : 'Crie sua conta'}</h2><p>{mode === 'login' ? 'Entre com os dados cadastrados na Vita Fortis.' : 'Preencha seus dados para começar.'}</p><div className="auth-switch"><button className={mode === 'login' ? 'active' : ''} onClick={() => { setMode('login'); setError('') }}>Entrar</button><button className={mode === 'register' ? 'active' : ''} onClick={() => { setMode('register'); setError('') }}>Cadastrar</button></div><form onSubmit={submit} className="form">{mode === 'register' && <><label>Nome completo<input name="nome" required maxLength={120} autoComplete="name" /></label><div className="form-row"><label>CPF<input name="cpf" required placeholder="000.000.000-00" inputMode="numeric" /></label><label>Telefone<input name="telefone" maxLength={20} autoComplete="tel" /></label></div></>}<label>E-mail<input name="email" required type="email" autoComplete="email" /></label><label>Senha<div className="password-field"><input name="senha" required type={show ? 'text' : 'password'} minLength={mode === 'register' ? 8 : undefined} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} /><button type="button" onClick={() => setShow(!show)} aria-label={show ? 'Ocultar senha' : 'Mostrar senha'}>{show ? <EyeOff /> : <Eye />}</button></div>{mode === 'register' && <small>Mínimo de 8 caracteres.</small>}</label>{error && <div className="form-error" role="alert">{error}</div>}<button className="button primary" disabled={busy}>{busy ? 'Aguarde…' : mode === 'login' ? 'Entrar' : 'Criar conta'}</button></form><p className="security-copy">Sua senha é usada apenas para autenticar cada chamada ao backend e permanece nesta sessão do navegador. O backend ainda não oferece tokens.</p></section></div>
}

