import { Search, SlidersHorizontal, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { ProductCard } from '../components/ProductCard'
import { Empty, ErrorState, Loading } from '../components/States'
import { api } from '../services/api'
import type { CategorySummary, Page, Product } from '../types/api'
import { titleCase } from '../utils/format'
const supported = new Set(['busca','marca','categoria','precoMin','precoMax','ordenacao','pagina','tamanho','objetivos','esportes','vegano','vegetariano','linhaClinica','lancamento','subcategoria','avaliacaoMedia','oferta','emEstoque','descontoMin','maisVendidos'])
export function CatalogPage() {
  const [params,setParams] = useSearchParams(); const [page,setPage] = useState<Page<Product>|null>(null); const [categories,setCategories] = useState<CategorySummary[]>([]); const [loading,setLoading] = useState(true); const [error,setError] = useState(''); const [filtersOpen,setFiltersOpen] = useState(false)
  const key = params.toString(); const apiFilters = useMemo(() => Object.fromEntries([...params].filter(([name]) => supported.has(name))), [key])
  const load = () => { setLoading(true); setError(''); api.products({ ...apiFilters, pagina: Number(params.get('pagina') || 0), tamanho: 12 }).then(setPage).catch((e:Error) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(load,[key]); useEffect(() => { api.categories().then(setCategories).catch(() => undefined) },[])
  const set = (name:string,value:string) => { const next = new URLSearchParams(params); if (value) next.set(name,value); else next.delete(name); if (name !== 'pagina') next.delete('pagina'); setParams(next) }; const active = [...params].filter(([name]) => name !== 'pagina')
  const title = params.get('categoria') ? titleCase(params.get('categoria')!) : params.get('marca') ? `Produtos ${params.get('marca')}` : params.get('oferta') ? 'Ofertas Vita Fortis' : 'Produtos para o seu objetivo'
  return <div className="page container"><header className="page-header catalog-header"><span className="eyebrow">Catálogo</span><h1>{title}</h1><p>Busca, disponibilidade e filtros comerciais em uma única experiência.</p></header>
    <div className="catalog-toolbar"><label className="catalog-search"><Search size={18}/><input value={params.get('busca') || ''} onChange={(e) => set('busca',e.target.value)} placeholder="Buscar produto, descrição ou marca" /></label><button className="button secondary filter-toggle" onClick={() => setFiltersOpen(!filtersOpen)}><SlidersHorizontal size={17}/> Filtrar</button><label>Ordenar<select value={params.get('ordenacao') || ''} onChange={(e) => set('ordenacao',e.target.value)}><option value="">Relevância</option><option value="NOME_ASC">Nome A–Z</option><option value="PRECO_ASC">Menor preço</option><option value="PRECO_DESC">Maior preço</option></select></label></div>
    {active.length > 0 && <div className="filter-chips">{active.map(([name,value]) => <button key={name} onClick={() => set(name,'')}>{titleCase(name)}: {titleCase(value)} <X size={13}/></button>)}<button className="clear" onClick={() => setParams({})}>Limpar todos</button></div>}
    <div className="catalog-layout"><aside className={`filters ${filtersOpen ? 'open' : ''}`}><div className="filters-title"><h2>Filtros</h2><button onClick={() => setFiltersOpen(false)} aria-label="Fechar"><X/></button></div><fieldset><legend>Categoria</legend><button className={!params.get('categoria') ? 'active' : ''} onClick={() => set('categoria','')}>Todas</button>{categories.map((item) => <button key={item.categoria} className={params.get('categoria') === item.categoria ? 'active' : ''} onClick={() => set('categoria',item.categoria)}>{titleCase(item.categoria)} <small>{item.quantidadeProdutos}</small></button>)}</fieldset><fieldset><legend>Marca</legend><input value={params.get('marca') || ''} onChange={(e) => set('marca',e.target.value)} placeholder="Ex.: Growth" /></fieldset><fieldset><legend>Faixa de preço</legend><div className="range-fields"><input type="number" min="0" placeholder="Mín." value={params.get('precoMin') || ''} onChange={(e) => set('precoMin',e.target.value)}/><input type="number" min="0" placeholder="Máx." value={params.get('precoMax') || ''} onChange={(e) => set('precoMax',e.target.value)}/></div></fieldset></aside>
      <section className="catalog-results">{page && <p className="result-count">{page.totalElements} {page.totalElements === 1 ? 'produto encontrado' : 'produtos encontrados'}</p>}{loading ? <Loading/> : error ? <ErrorState message={error} retry={load}/> : !page?.content.length ? <Empty title="Nenhum produto encontrado" text="Remova algum filtro ou faça uma nova busca."/> : <><div className="product-grid">{page.content.map((p) => <ProductCard key={p.id} product={p}/>)}</div><div className="pagination"><button disabled={page.first} onClick={() => set('pagina',String(page.number - 1))}>Anterior</button><span>Página {page.number + 1} de {page.totalPages}</span><button disabled={page.last} onClick={() => set('pagina',String(page.number + 1))}>Próxima</button></div></>}</section></div></div>
}


