import { BadgeDollarSign, BarChart3, Download, ReceiptText, TicketPercent } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Navigate } from 'react-router-dom'
import { useAuth } from '../app/AuthContext'
import { ErrorState, Empty, Loading } from '../components/States'
import { api } from '../services/api'
import { isCollaborator, type CollaboratorSummary } from '../types/api'
import { date, money, titleCase } from '../utils/format'

export function CollaboratorPage(){
 const {user}=useAuth();const [data,setData]=useState<CollaboratorSummary|null>(null);const [error,setError]=useState('');const [type,setType]=useState('');const [coupon,setCoupon]=useState('');const [start,setStart]=useState('');const [end,setEnd]=useState('')
 const load=()=>{setError('');api.collaboratorSummary().then(setData).catch((e:Error)=>setError(e.message))};useEffect(()=>{if(isCollaborator(user))void load()},[user])
 const filtered=useMemo(()=>data?.movimentos.filter(m=>(!type||m.tipo===type)&&(!start||m.criadoEm.slice(0,10)>=start)&&(!end||m.criadoEm.slice(0,10)<=end))||[],[data,type,start,end])
 const orders=useMemo(()=>data?.pedidos.filter(o=>!coupon||o.cupomCodigo===coupon)||[],[data,coupon])
 if(!user)return <Navigate to="/entrar" replace/>;if(!isCollaborator(user))return <Navigate to={user.tipoUsuario==='ADMIN'?'/admin':'/conta'} replace/>
 return <div className="page container collaborator-page"><header className="page-header compact"><span className="eyebrow">Área do colaborador</span><h1>Olá, {user.nome.split(' ')[0]}.</h1><p>Acompanhe somente os cupons, vendas e cashback vinculados à sua conta.</p></header>{error?<ErrorState message={error} retry={load}/>:!data?<Loading/>:<>
 <div className="metric-grid"><article><BadgeDollarSign/><span>Saldo disponível</span><strong>{money(data.saldo)}</strong></article><article><BarChart3/><span>Vendas geradas</span><strong>{money(data.vendasGeradas)}</strong><small>{data.pedidosGerados} pedido(s)</small></article><article><ReceiptText/><span>Cashback confirmado</span><strong>{money(data.cashbackConfirmado)}</strong><small>{money(data.cashbackEstornado)} estornado</small></article></div>
 <div className="collaborator-grid"><section className="chart-card"><h2><TicketPercent size={18}/> Desempenho dos meus cupons</h2>{!data.cupons.length?<Empty title="Nenhum cupom vinculado" text="Solicite ao administrador o vínculo de um cupom."/>:<div className="table-wrap"><table><thead><tr><th>Cupom</th><th>Cashback</th><th>Pedidos</th><th>Vendas</th><th>Gerado</th></tr></thead><tbody>{data.cupons.map(c=><tr key={c.id}><td><strong>{c.codigo}</strong><small>{c.ativo?'Ativo':'Inativo'}</small></td><td>{c.percentualCashback}%</td><td>{c.pedidos}</td><td>{money(c.vendas)}</td><td>{money(c.cashback)}</td></tr>)}</tbody></table></div>}</section>
 <section className="chart-card"><h2>Extrato auditável</h2><div className="filter-row"><select value={type} onChange={e=>setType(e.target.value)}><option value="">Todos os movimentos</option>{['CREDITO','ESTORNO','AJUSTE','BAIXA'].map(v=><option key={v}>{v}</option>)}</select><input type="date" value={start} onChange={e=>setStart(e.target.value)}/><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div>{!filtered.length?<Empty title="Sem movimentações" text="Ajuste os filtros ou aguarde a aprovação de pedidos."/>:<div className="movement-list">{filtered.map(m=><article key={m.id}><div><strong>{titleCase(m.tipo)}</strong><small>{date(m.criadoEm)} {m.pedidoId&&`• Pedido #${m.pedidoId}`}</small><span>{m.justificativa}</span></div><b className={m.valor<0?'negative':'positive'}>{m.valor>0?'+':''}{money(m.valor)}</b></article>)}</div>}</section></div>
 <section className="chart-card"><header><div><h2>Pedidos atribuídos</h2><p>Somente pedidos associados aos seus cupons.</p></div><select value={coupon} onChange={e=>setCoupon(e.target.value)}><option value="">Todos os cupons</option>{data.cupons.map(c=><option key={c.id}>{c.codigo}</option>)}</select></header>{!orders.length?<p className="empty-inline">Nenhum pedido encontrado.</p>:<div className="table-wrap"><table><thead><tr><th>Pedido</th><th>Data</th><th>Cupom</th><th>Status</th><th>Total</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>#{o.id}</td><td>{date(o.dataPedido)}</td><td>{o.cupomCodigo}</td><td>{titleCase(o.status)}</td><td>{money(o.total)}</td></tr>)}</tbody></table></div>}</section>
 {user.permissaoRelatorios&&<section className="chart-card"><h2><Download/> Relatórios autorizados</h2><p>Exporte métricas do período sem acessar cadastros administrativos.</p><div className="report-actions">{['PEDIDOS','CUPONS','CASHBACK'].map(tipo=><button className="button secondary" key={tipo} onClick={()=>void api.downloadReport(tipo,start||new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10),end||new Date().toISOString().slice(0,10))}><Download/> {titleCase(tipo)}</button>)}</div></section>}</>}</div>
}
