import { ArrowRight, ChevronLeft, ChevronRight, Headphones, Leaf, RotateCcw, ShieldCheck, Sparkles, Truck } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { ProductCard } from '../components/ProductCard'
import { ErrorState, Loading } from '../components/States'
import { campaigns, goals, sports } from '../data/demo'
import { api } from '../services/api'
import type { Product } from '../types/api'

const categories = [
  ['PROTEINAS','Proteínas','/assets/imagens/proteina_telafiltraveis.jpg'], ['VITAMINAS','Vitaminas','/assets/imagens/vitamina_telafiltraveis'], ['TERMOGENICOS','Termogênicos','/assets/imagens/termogenico_telafiltraveis'], ['KITS','Kits','/assets/imagens/proteina_exemplo.png'],
]
export function HomePage() {
  const [products, setProducts] = useState<Product[]>([]); const [best,setBest]=useState<Product[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [slide, setSlide] = useState(0); const [paused, setPaused] = useState(false)
  const touchStart = useRef<number | null>(null)
  const load = () => { setLoading(true); setError(''); Promise.all([api.products({ tamanho: 12, ordenacao: 'NOME_ASC' }),api.products({tamanho:4,destaque:true})]).then(([page,featured]) => {setProducts(page.content);setBest(featured.content)}).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(load, []); useEffect(() => { if (paused) return; const timer = setInterval(() => setSlide((v) => (v + 1) % campaigns.length), 6500); return () => clearInterval(timer) }, [paused])
  const moveSlide = (direction: number) => setSlide((current) => (current + direction + campaigns.length) % campaigns.length)
  const finishSwipe = (clientX: number) => { if (touchStart.current === null) return; const distance = clientX - touchStart.current; if (Math.abs(distance) > 45) moveSlide(distance < 0 ? 1 : -1); touchStart.current = null }
  const campaign = campaigns[slide]; const offers = products.filter((p) => Number(p.precoFinal) < Number(p.preco)).slice(0, 4)
  return <>
    <section className="hero hero-carousel" onPointerEnter={() => setPaused(true)} onPointerLeave={() => setPaused(false)} onFocus={() => setPaused(true)} onBlur={() => setPaused(false)} onTouchStart={(event) => { touchStart.current = event.touches[0].clientX }} onTouchEnd={(event) => finishSwipe(event.changedTouches[0].clientX)} aria-roledescription="carrossel" aria-label="Campanhas Vita Fortis"><div className="hero-backdrop" style={{ backgroundImage: `linear-gradient(90deg,rgba(8,35,25,.94),rgba(8,35,25,.35)),url('${campaign.image}')` }} /><div className="container hero-content"><span className="hero-kicker"><Sparkles size={16} /> {campaign.eyebrow}</span><h1>{campaign.title}</h1><p>{campaign.text}</p><Link className="button primary" to={campaign.to}>Conhecer seleção <ArrowRight size={18} /></Link></div><button className="hero-arrow left" onClick={() => moveSlide(-1)} aria-label="Banner anterior"><ChevronLeft /></button><button className="hero-arrow right" onClick={() => moveSlide(1)} aria-label="Próximo banner"><ChevronRight /></button><div className="hero-dots">{campaigns.map((item,i) => <button key={item.title} className={i === slide ? 'active' : ''} onClick={() => setSlide(i)} aria-label={`Exibir banner ${i + 1}`} aria-current={i === slide ? 'true' : undefined} />)}</div></section>
    <section className="benefits container"><div><Truck /><span><strong>Pedido simplificado</strong>Finalize online</span></div><div><ShieldCheck /><span><strong>Compra segura</strong>Dados protegidos</span></div><div><Headphones /><span><strong>Atendimento humano</strong>Conte com a equipe</span></div><div><RotateCcw /><span><strong>Troca facilitada</strong>Acompanhamento próximo</span></div></section>
    <section className="section container intent-section"><div className="section-heading"><div><span className="eyebrow">Comece por você</span><h2>EU QUERO...</h2><p>Escolha seu objetivo e encontre produtos relacionados.</p></div></div><div className="goal-grid">{goals.map(([value,label],i) => <Link key={value} to={`/catalogo?objetivos=${value}`}><span>0{i + 1}</span>{label}<ArrowRight /></Link>)}</div></section>
    <section className="section container"><div className="section-heading"><div><span className="eyebrow">Condições especiais</span><h2>Ofertas para aproveitar agora</h2></div><Link className="text-link" to="/ofertas">Ver ofertas <ArrowRight size={16} /></Link></div>{loading ? <Loading label="Buscando produtos…" /> : error ? <ErrorState message={error} retry={load} /> : <div className="product-grid">{(offers.length ? offers : best).map((p) => <ProductCard key={p.id} product={p} />)}</div>}</section>
    <section className="category-section"><div className="container"><div className="section-heading"><div><span className="eyebrow light">Por categoria</span><h2>Escolhas para cada rotina</h2></div></div><div className="category-grid expanded">{categories.map(([value,label,image]) => <Link to={`/catalogo?categoria=${value}`} className="category-card" key={value}><img src={image} onError={(e) => { e.currentTarget.src = '/assets/imagens/proteina_exemplo.png' }} alt="" /><span>{label}<ArrowRight /></span></Link>)}</div></div></section>
    <section className="section container"><div className="section-heading"><div><span className="eyebrow">Seleção Vita Fortis</span><h2>Produtos em destaque</h2></div></div>{best.length?<div className="product-grid">{best.map((p) => <ProductCard key={p.id} product={p} />)}</div>:!loading&&!error&&<p className="empty-inline">Os destaques aparecerão quando forem selecionados no painel.</p>}</section>
    <section className="sport-section"><div className="container"><span className="eyebrow light">Escolha por modalidade</span><h2>Qual é o seu esporte?</h2><div className="sport-grid">{sports.map(([value,label,image]) => <Link key={value} to={`/catalogo?esporte=${value}`}><img src={image} onError={(e) => { e.currentTarget.src = '/assets/imagens/banner-foto-1.jpg' }} alt="" /><strong>{label}</strong></Link>)}</div></div></section>
    <section className="section container"><div className="shortcut-grid"><Link to="/novidades"><Sparkles /><strong>Novidades</strong><span>Conheça os lançamentos</span></Link><Link to="/kits"><Leaf /><strong>Kits</strong><span>Combinações para sua rotina</span></Link><Link to="/ofertas"><ArrowRight /><strong>Ofertas</strong><span>Condições especiais</span></Link><Link to="/marcas"><ShieldCheck /><strong>Marcas</strong><span>Encontre suas preferidas</span></Link></div></section>
  </>
}
