import { ArrowRight, ChevronLeft, ChevronRight, Headphones, Leaf, RotateCcw, ShieldCheck, Sparkles, Truck } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ProductCard } from '../components/ProductCard'
import { ErrorState, Loading } from '../components/States'
import { campaigns, goals, sports } from '../data/demo'
import { api } from '../services/api'
import type { Product } from '../types/api'

const categories = [
  ['PROTEINAS','Proteínas','/assets/imagens/proteina_telafiltraveis.jpg'], ['AMINOACIDOS','Aminoácidos','/assets/imagens/aminoacidos_telafiltraveis'], ['VITAMINAS','Vitaminas','/assets/imagens/vitamina_telafiltraveis'], ['TERMOGENICOS','Termogênicos','/assets/imagens/termogenico_telafiltraveis'], ['CARBOIDRATOS','Carboidratos','/assets/imagens/carboidrato_telafiltraveis'], ['LINHA_CLINICA','Linha clínica','/assets/imagens/clinical_telafiltraveis'], ['VEGETARIANOS','Vegetarianos','/assets/imagens/vegetariano_telafiltraveis'], ['VEGANOS','Veganos','/assets/imagens/vegano_telafiltraveis'], ['ACESSORIOS','Acessórios','/assets/imagens/imagem-com-fundo-chat.categorias.png'], ['KITS','Kits','/assets/imagens/proteina_exemplo.png'],
]
export function HomePage() {
  const [products, setProducts] = useState<Product[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [slide, setSlide] = useState(0); const [paused, setPaused] = useState(false)
  const load = () => { setLoading(true); setError(''); api.products({ tamanho: 12, ordenacao: 'NOME_ASC' }).then((page) => setProducts(page.content)).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(load, []); useEffect(() => { if (paused) return; const timer = setInterval(() => setSlide((v) => (v + 1) % campaigns.length), 6500); return () => clearInterval(timer) }, [paused])
  const campaign = campaigns[slide]; const offers = products.filter((p) => Number(p.precoFinal) < Number(p.preco)).slice(0, 4); const best = products.slice(0, 4)
  return <>
    <section className="hero hero-carousel" onPointerEnter={() => setPaused(true)} onPointerLeave={() => setPaused(false)} aria-roledescription="carrossel"><div className="hero-backdrop" style={{ backgroundImage: `linear-gradient(90deg,rgba(8,35,25,.94),rgba(8,35,25,.35)),url('${campaign.image}')` }} /><div className="container hero-content"><span className="hero-kicker"><Sparkles size={16} /> {campaign.eyebrow}</span><h1>{campaign.title}</h1><p>{campaign.text}</p><Link className="button primary" to={campaign.to}>Conhecer seleção <ArrowRight size={18} /></Link></div><button className="hero-arrow left" onClick={() => setSlide((slide - 1 + campaigns.length) % campaigns.length)} aria-label="Banner anterior"><ChevronLeft /></button><button className="hero-arrow right" onClick={() => setSlide((slide + 1) % campaigns.length)} aria-label="Próximo banner"><ChevronRight /></button><div className="hero-dots">{campaigns.map((item,i) => <button key={item.title} className={i === slide ? 'active' : ''} onClick={() => setSlide(i)} aria-label={`Exibir banner ${i + 1}`} />)}</div></section>
    <section className="benefits container"><div><Truck /><span><strong>Pedido simplificado</strong>Finalize online</span></div><div><ShieldCheck /><span><strong>Compra segura</strong>Dados protegidos</span></div><div><Headphones /><span><strong>Atendimento humano</strong>Conte com a equipe</span></div><div><RotateCcw /><span><strong>Troca facilitada</strong>Acompanhamento próximo</span></div></section>
    <section className="section container"><div className="section-heading"><div><span className="eyebrow">Encontre seu caminho</span><h2>O que você procura?</h2></div></div><div className="goal-grid">{goals.map(([value,label],i) => <Link key={value} to={i === 0 ? '/catalogo?maisVendidos=true' : `/catalogo?objetivo=${value}`}><span>0{i + 1}</span>{label}<ArrowRight /></Link>)}</div></section>
    <section className="section container"><div className="section-heading"><div><span className="eyebrow">Condições especiais</span><h2>Ofertas para aproveitar agora</h2></div><Link className="text-link" to="/ofertas">Ver ofertas <ArrowRight size={16} /></Link></div>{loading ? <Loading label="Buscando produtos…" /> : error ? <ErrorState message={error} retry={load} /> : <div className="product-grid">{(offers.length ? offers : best).map((p) => <ProductCard key={p.id} product={p} />)}</div>}</section>
    <section className="category-section"><div className="container"><div className="section-heading"><div><span className="eyebrow light">Por categoria</span><h2>Escolhas para cada rotina</h2></div></div><div className="category-grid expanded">{categories.map(([value,label,image]) => <Link to={`/catalogo?categoria=${value}`} className="category-card" key={value}><img src={image} onError={(e) => { e.currentTarget.src = '/assets/imagens/proteina_exemplo.png' }} alt="" /><span>{label}<ArrowRight /></span></Link>)}</div></div></section>
    <section className="section container"><div className="section-heading"><div><span className="eyebrow">Preferidos da comunidade</span><h2>Mais vendidos</h2><p className="demo-label">Seleção demonstrativa enquanto a API não fornece ranking.</p></div></div><div className="product-grid">{best.map((p) => <ProductCard key={p.id} product={p} />)}</div></section>
    <section className="sport-section"><div className="container"><span className="eyebrow light">Escolha por modalidade</span><h2>Qual é o seu esporte?</h2><div className="sport-grid">{sports.map(([value,label,image]) => <Link key={value} to={`/catalogo?esporte=${value}`}><img src={image} onError={(e) => { e.currentTarget.src = '/assets/imagens/banner-foto-1.jpg' }} alt="" /><strong>{label}</strong></Link>)}</div></div></section>
    <section className="section container"><div className="shortcut-grid"><Link to="/novidades"><Sparkles /><strong>Novidades</strong><span>Conheça os lançamentos</span></Link><Link to="/kits"><Leaf /><strong>Kits</strong><span>Combinações para sua rotina</span></Link><Link to="/ofertas"><ArrowRight /><strong>Outlet e ofertas</strong><span>Condições especiais</span></Link><Link to="/favoritos"><ShieldCheck /><strong>Favoritos</strong><span>Reveja suas escolhas</span></Link></div></section>
  </>
}
