import { CheckCircle2, Clock3, Package } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, Navigate, useSearchParams } from 'react-router-dom'
import { useAuth } from '../app/AuthContext'
import { Empty, ErrorState, Loading } from '../components/States'
import { api } from '../services/api'
import type { Order } from '../types/api'
import { date, money, titleCase } from '../utils/format'

export function OrdersPage() { const { user } = useAuth(); const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [params] = useSearchParams(); const load = () => { if (!user) return; setLoading(true); api.orders(user.id).then(setOrders).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }; useEffect(load, [user]); if (!user) return <Navigate to="/entrar" replace />; return <div className="page container"><header className="page-header compact"><span className="eyebrow">Histórico</span><h1>Meus pedidos</h1><p>Acompanhe os estados registrados pela Vita Fortis.</p></header>{params.get('novo') && <div className="success-banner"><CheckCircle2 /><div><strong>Pedido #{params.get('novo')} criado!</strong><span>O pedido foi registrado e aguarda a confirmação administrativa do pagamento simulado.</span></div></div>}{loading ? <Loading /> : error ? <ErrorState message={error} retry={load} /> : !orders.length ? <><Empty title="Nenhum pedido ainda" text="Quando você finalizar sua primeira compra, ela aparecerá aqui." /><div className="center"><Link className="button primary" to="/catalogo">Ir ao catálogo</Link></div></> : <div className="order-list">{orders.map((order) => <article className="order-card" key={order.id}><header><div><span>Pedido #{order.id}</span><small>{date(order.dataPedido)}</small></div><b className={`status ${order.status.toLowerCase()}`}><Clock3 /> {titleCase(order.status)}</b></header>{order.statusPagamento==='PENDENTE'&&<div className="payment-pending"><Clock3/><div><strong>Pagamento aguardando confirmação</strong><span>{titleCase(order.formaPagamento||'simulado')} {order.referenciaPagamentoMascarada&&`• Referência ${order.referenciaPagamentoMascarada}`}</span></div></div>}<div className="order-items">{order.itens.map((item) => <div key={item.id}><span><Package /> {item.quantidade}× {item.produtoNome}</span><strong>{money(item.subtotal)}</strong></div>)}</div><footer><span>{titleCase(order.formaRecebimento)} • {titleCase(order.statusPagamento)}</span><strong>{money(order.total)}</strong></footer></article>)}</div>}</div> }
