CREATE TABLE solicitacao_privacidade (
    SOLICITACAO_ID BIGINT NOT NULL AUTO_INCREMENT,
    USUARIO_ID BIGINT NOT NULL,
    PROTOCOLO VARCHAR(40) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    DESCRICAO VARCHAR(1000) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    DECISAO VARCHAR(500) NULL,
    JUSTIFICATIVA_ADMIN VARCHAR(1000) NULL,
    RESPONSAVEL VARCHAR(255) NULL,
    PROCESSADA_EM DATETIME NULL,
    CRIADA_EM DATETIME NOT NULL,
    ATUALIZADA_EM DATETIME NOT NULL,
    PRIMARY KEY (SOLICITACAO_ID),
    CONSTRAINT UK_SOLICITACAO_PRIVACIDADE_PROTOCOLO UNIQUE (PROTOCOLO),
    CONSTRAINT FK_SOLICITACAO_PRIVACIDADE_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES usuario (USUARIO_ID)
);

CREATE INDEX IDX_SOLICITACAO_PRIVACIDADE_USUARIO_DATA
    ON solicitacao_privacidade (USUARIO_ID, CRIADA_EM);

CREATE TABLE auditoria_solicitacao_privacidade (
    AUDITORIA_ID BIGINT NOT NULL AUTO_INCREMENT,
    SOLICITACAO_ID BIGINT NOT NULL,
    STATUS_ANTERIOR VARCHAR(20) NOT NULL,
    STATUS_NOVO VARCHAR(20) NOT NULL,
    DECISAO VARCHAR(500) NOT NULL,
    JUSTIFICATIVA VARCHAR(1000) NOT NULL,
    RESPONSAVEL VARCHAR(255) NOT NULL,
    CRIADA_EM DATETIME NOT NULL,
    PRIMARY KEY (AUDITORIA_ID),
    CONSTRAINT FK_AUDITORIA_PRIVACIDADE_SOLICITACAO FOREIGN KEY (SOLICITACAO_ID)
        REFERENCES solicitacao_privacidade (SOLICITACAO_ID)
);

CREATE INDEX IDX_AUDITORIA_PRIVACIDADE_SOLICITACAO_DATA
    ON auditoria_solicitacao_privacidade (SOLICITACAO_ID, CRIADA_EM);
