package VitaFortis.demo.v1.service;
import VitaFortis.demo.v1.dto.MetricasAdminDto; import VitaFortis.demo.v1.entity.*; import VitaFortis.demo.v1.repository.*; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.*; import java.time.format.DateTimeFormatter; import java.util.*; import java.util.stream.*;
@Service public class MetricasService {private final PedidoRepository pedidos;private final UsuarioRepository usuarios;public MetricasService(PedidoRepository p,UsuarioRepository u){pedidos=p;usuarios=u;}
 @Transactional(readOnly=true) public MetricasAdminDto obter(LocalDate inicio,LocalDate fim,String email){var atual=usuarios.findByEmail(email).orElseThrow(()->new AccessDeniedException("Usuario nao autenticado"));if(atual.getTipo().name().equals("CLIENTE")||(atual.getTipo().name().equals("COLABORADOR")&&!atual.isPermissaoRelatorios()))throw new AccessDeniedException("Sem permissao de relatorio");if(fim.isBefore(inicio))throw new IllegalArgumentException("fim deve ser igual ou posterior a inicio");
  var lista=pedidos.findByDataPedidoBetween(inicio.atStartOfDay(),fim.plusDays(1).atStartOfDay()).stream().filter(p->p.getStatus()!=VitaFortis.demo.v1.enums.StatusCompra.CANCELADO).toList();long dias=java.time.temporal.ChronoUnit.DAYS.between(inicio,fim)+1;var anterior=pedidos.findByDataPedidoBetween(inicio.minusDays(dias).atStartOfDay(),inicio.atStartOfDay()).stream().filter(p->p.getStatus()!=VitaFortis.demo.v1.enums.StatusCompra.CANCELADO).toList();
  BigDecimal fat=soma(lista),fatAnt=soma(anterior),comp=fatAnt.signum()==0?BigDecimal.ZERO:fat.subtract(fatAnt).multiply(BigDecimal.valueOf(100)).divide(fatAnt,2,RoundingMode.HALF_UP);long qtd=lista.size(),prod=lista.stream().flatMap(p->p.getItems().stream()).mapToLong(ItemCompra::getQuantidade).sum(),clientes=lista.stream().map(p->p.getUsuario().getId()).distinct().count();
  return new MetricasAdminDto(fat,qtd,qtd==0?BigDecimal.ZERO:fat.divide(BigDecimal.valueOf(qtd),2,RoundingMode.HALF_UP),prod,clientes,comp,serie(lista,"yyyy-MM-dd"),serie(lista,"yyyy-MM"),contagemCategorias(lista),lista.stream().collect(Collectors.groupingBy(p->p.getStatus().name(),Collectors.counting())),maisVendidos(lista),lista.stream().sorted(Comparator.comparing(Pedido::getDataPedido).reversed()).limit(20).map(p->new MetricasAdminDto.VendaRecenteDto(p.getId(),p.getDataPedido(),p.getUsuario().getNome(),p.getTotal(),p.getStatus().name())).toList());}
 private BigDecimal soma(List<Pedido> l){return l.stream().map(Pedido::getTotal).reduce(BigDecimal.ZERO,BigDecimal::add);}
 private List<MetricasAdminDto.PontoSerieDto> serie(List<Pedido> l,String fmt){return l.stream().collect(Collectors.groupingBy(p->p.getDataPedido().format(DateTimeFormatter.ofPattern(fmt)),TreeMap::new,Collectors.toList())).entrySet().stream().map(e->new MetricasAdminDto.PontoSerieDto(e.getKey(),soma(e.getValue()),e.getValue().size())).toList();}
 private Map<String,Long> contagemCategorias(List<Pedido> l){return l.stream().flatMap(p->p.getItems().stream()).collect(Collectors.groupingBy(i->i.getProduto().getCategoria().name(),Collectors.summingLong(ItemCompra::getQuantidade)));}
 private List<MetricasAdminDto.ProdutoVendidoDto> maisVendidos(List<Pedido> l){return l.stream().flatMap(p->p.getItems().stream()).collect(Collectors.groupingBy(i->i.getProduto().getId())).entrySet().stream().map(e->{var it=e.getValue();return new MetricasAdminDto.ProdutoVendidoDto(e.getKey(),it.get(0).getProduto().getNome(),it.stream().mapToLong(ItemCompra::getQuantidade).sum(),it.stream().map(ItemCompra::getSubtotal).reduce(BigDecimal.ZERO,BigDecimal::add));}).sorted(Comparator.comparingLong(MetricasAdminDto.ProdutoVendidoDto::quantidade).reversed()).limit(10).toList();}
}
